package com.carboexco.modulo_usuario.security;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

import java.io.IOException;
import java.util.Collections;

public class JWTAuthenticationFilter extends UsernamePasswordAuthenticationFilter {

    @Override
    public Authentication attemptAuthentication(HttpServletRequest request, HttpServletResponse response) throws AuthenticationException {

       AuthCredentials authCredentials =new AuthCredentials();

       try {
           authCredentials = new ObjectMapper().readValue(request.getReader(), AuthCredentials.class);
       }catch (IOException e){}

        UsernamePasswordAuthenticationToken USERNAMEpAT = new UsernamePasswordAuthenticationToken(
                authCredentials.getCodigo_Radio(),
                authCredentials.getPassword(),
                Collections.emptyList());
        return super.attemptAuthentication(request, response);
    }

    @Override
    protected void successfulAuthentication(HttpServletRequest request,
                                            HttpServletResponse response,
                                            FilterChain chain,
                                            Authentication authResult) throws IOException, ServletException {

        UserDetailImpl userDetails = (UserDetailImpl) authResult.getPrincipal();
        String token = TokenUtils.createToken(userDetails.getNombre(), userDetails.getUsername());

        response.addHeader("Authorization", "AUTHENTICATION TOKEN GENERATED BY THE SYSTEMS DEPARTMENT" + token);
        response.getWriter().flush();
        super.successfulAuthentication(request, response, chain, authResult);
    }
}
